export const NICHE_SUGGESTIONS = [
  "Médico",
  "Advogado",
  "Infoprodutor",
  "Clínica estética",
  "Mentor",
  "Agência",
  "Arquiteto",
  "Nutricionista",
  "Psicólogo",
  "Dentista",
  "Prestador de serviço",
  "Consultor",
  "Terapeuta",
  "Educador físico",
  "Especialista em beleza",
  "Coach",
  "Fisioterapeuta",
  "Contador",
  "Imobiliária",
  "Fotógrafo",
  "Salão de beleza",
  "Petshop",
  "Restaurante",
  "E-commerce",
] as const;
